// THE CHART. A branching map of the water, read from the bottom up.
//
// The old map was three islands on the horizon and you picked one. That is a choice, but it is
// the SAME choice fourteen times: three cards, one of them is the dangerous one, sail. There
// is no route, so there is nothing to plan and nothing to regret -- and a run-based game whose
// map has no shape is a run-based game whose runs are all the same shape.
//
// So: a lattice. Rows of stops going away from you, edges between them, and you may only ever
// move UP and to an ADJACENT column. Which means the interesting decision is not "which of
// these three" but "which of these three, given the four rows behind it" -- you take the safe
// stop now because the only path to the shop goes through the elite two rows up, and you
// cannot come back for it.
//
// WHAT MAKES A LATTICE WORK, and all three of these are load-bearing:
//
//   EVERY NODE IS REACHABLE AND EVERY NODE LEADS ON. A stop with no way in is scenery and a
//   stop with no way out is a trap; both are generated by accident by any naive edge roll, and
//   both are fixed here rather than being drawn round.
//
//   EDGES NEVER CROSS. If A is left of B in one row and their targets are the other way round
//   in the next, the two lines cross and the player cannot tell which one they are on. Two
//   lines that swap over is not a hard read, it is an unreadable one.
//
//   THE LAST TWO ROWS ARE FIXED. The row below the boss is always a rest, because arriving at
//   a boss with no chance to spend or mend is a coin flip rather than a fight, and the first
//   row is always an ordinary landing, because the first thing a run should teach is the verb.
//
// Nothing here draws and nothing here knows about the voyage. It is a graph with labels.

import { makeRng } from '../core/rng.js';

export const KINDS = {
  fight: {
    id: 'fight', name: 'A SHORE', color: 'leaf2', icon: 'paw',
    blurb: 'Corrupted animals on a beach. Beat them, load them.',
  },
  elite: {
    id: 'elite', name: 'A BAD SHORE', color: 'red2', icon: 'skull',
    blurb: 'Something big is already ashore. Worth more than it costs.',
  },
  shop: {
    id: 'shop', name: 'THE GARDEN', color: 'brass3', icon: 'coin',
    blurb: 'Dry ground. Spend, stow, and mend the hull.',
  },
  event: {
    id: 'event', name: 'SOMETHING ON THE WATER', color: 'water3', icon: 'mark',
    blurb: 'A decision. They are never free and they are never nothing.',
  },
  rest: {
    id: 'rest', name: 'A QUIET COVE', color: 'moss2', icon: 'fire',
    blurb: 'Feed what you have. Nothing here wants anything from you.',
  },
  boss: {
    id: 'boss', name: 'THE DEEP', color: 'purple1', icon: 'crown',
    blurb: 'It has been following the boat since the rain started.',
  },
};

export const KIND_IDS = Object.keys(KINDS);

// SIX ROWS, AND IT HAS TO MATCH THE CHAPTER. The first cut was eleven -- a proper act-length
// lattice -- against a voyage of four chapters of four legs each, so the chart's boss sat six
// rows above anywhere a run could ever reach: every chapter was the bottom third of a map you
// never saw the top of, and the harness reported `boss -` on every voyage for a week. Six rows
// and six legs a chapter: one shore, three rows of real choice, a cove, and the thing at the
// top of the water. Four chapters of that is twenty-four stops, which is a run.
const ROWS = 6;
const MAX_COLS = 4;

/* ------------------------------------------------------------------ building */

/**
 * How many stops a row has.
 *
 * NEVER FOUR TWICE IN A ROW and never two ones together: a map that is four wide all the way
 * up is a grid rather than a route, and a map that necks down to one twice reads as two
 * separate maps. Widths that breathe are what make the shape memorable.
 */
function widthFor(row, rng, prev) {
  if (row === 0) return 3;
  if (row === ROWS - 1) return 1;             // the boss
  if (row === ROWS - 2) return 2;             // and the cove in front of it
  const roll = rng();
  let w = roll < 0.18 ? 2 : roll < 0.66 ? 3 : 4;
  if (prev === 4 && w === 4) w = 3;
  if (prev === 2 && w === 2) w = 3;
  return w;
}

/**
 * What kind of stop.
 *
 * The weights matter less than the RULES around them. An elite in the first three rows kills
 * runs that have not been paid yet; two shops in the same row means the choice between them
 * is not a choice; and a rest immediately after a rest is a wasted row.
 */
function kindFor(row, rng, rowKinds, lastRowHadRest) {
  if (row === 0) return 'fight';
  if (row === ROWS - 1) return 'boss';
  if (row === ROWS - 2) return 'rest';
  const table = [];
  const push = (k, n) => { for (let i = 0; i < n; i++) table.push(k); };
  push('fight', 45);
  push('event', 22);
  // AN ELITE FROM ROW TWO, not row three: on a six-row chart "not until row three" meant not
  // until the row before the cove, so the run never met one until it no longer mattered.
  if (row >= 2) push('elite', row >= 3 ? 18 : 11);
  if (row >= 1 && !rowKinds.includes('shop')) push('shop', 13);
  if (!lastRowHadRest && !rowKinds.includes('rest')) push('rest', 9);
  return table[Math.floor(rng() * table.length)] || 'fight';
}

/**
 * The edges, and this is the only part that is subtle.
 *
 * Each node gets one or two edges up, to a column within one of its own. Then two repair
 * passes, because a naive roll leaves orphans about a third of the time:
 *
 *   anything in the next row with NO way in gets an edge from its nearest neighbour below
 *   anything in this row with NO way out gets an edge to its nearest neighbour above
 *
 * And the whole set is sorted and de-crossed: an edge from column i may not end left of an
 * edge from column i-1. That is what keeps two lines from swapping over, which is the
 * difference between a map you can read at a glance and a bowl of spaghetti.
 */
function linkRows(a, b, rng) {
  const nb = b.length;
  const colOf = (n, len) => (len === 1 ? 0.5 : n.col / (len - 1));
  // nearest node above, by normalised position
  const nearestAbove = (node) => {
    let best = 0, bd = 9;
    for (let j = 0; j < nb; j++) {
      const d = Math.abs(colOf(b[j], nb) - colOf(node, a.length));
      if (d < bd) { bd = d; best = j; }
    }
    return best;
  };
  for (const n of a) n.links = [];
  a.forEach((n) => {
    const near = nearestAbove(n);
    n.links.push(b[near].id);
    // a second edge, sideways by one, about half the time
    if (rng() < 0.46) {
      const alt = near + (rng() < 0.5 ? -1 : 1);
      if (alt >= 0 && alt < nb && !n.links.includes(b[alt].id)) n.links.push(b[alt].id);
    }
  });
  // every node above needs a way in
  for (let j = 0; j < nb; j++) {
    if (a.some((n) => n.links.includes(b[j].id))) continue;
    let best = 0, bd = 9;
    a.forEach((n, i) => {
      const d = Math.abs(colOf(b[j], nb) - colOf(n, a.length));
      if (d < bd) { bd = d; best = i; }
    });
    a[best].links.push(b[j].id);
  }
  // every node here needs a way on
  for (const n of a) if (!n.links.length) n.links.push(b[nearestAbove(n)].id);

  // DE-CROSS. Sort each node's links, then walk the row and clamp so the lowest target of
  // node i is never below the lowest target of node i-1.
  const ix = (id) => b.findIndex((x) => x.id === id);
  for (const n of a) n.links.sort((p, q) => ix(p) - ix(q));
  let floor = -1;
  for (const n of a) {
    n.links = n.links.filter((id) => ix(id) >= floor);
    if (!n.links.length) n.links = [b[Math.max(0, Math.min(nb - 1, floor))].id];
    floor = ix(n.links[0]);
  }
}

export function makeChart(seed = 'chart', chapter = 1) {
  const rng = makeRng(`chart:${seed}:${chapter}`);
  const rows = [];
  let id = 0;
  let prevW = 0;
  let lastRest = false;
  for (let r = 0; r < ROWS; r++) {
    const w = widthFor(r, rng, prevW);
    prevW = w;
    const row = [];
    const kinds = [];
    for (let c = 0; c < w; c++) {
      const kind = kindFor(r, rng, kinds, lastRest);
      kinds.push(kind);
      row.push({
        id: `n${id++}`, row: r, col: c, of: w, kind,
        links: [], done: false, danger: 0,
      });
    }
    lastRest = kinds.includes('rest');
    rows.push(row);
  }
  for (let r = 0; r < ROWS - 1; r++) linkRows(rows[r], rows[r + 1], rng);

  // DANGER RISES WITH THE ROW, and an elite is a row and a half harder than its neighbours.
  // One number, read off the map before you commit, and it has to mean what it says.
  for (const row of rows) {
    for (const n of row) {
      const base = 1 + (n.row / (ROWS - 1)) * 3.4;
      n.danger = Math.max(1, Math.round(base + (n.kind === 'elite' ? 1.6 : 0)
        + (n.kind === 'boss' ? 2.2 : 0)));
    }
  }

  return {
    seed, chapter, rows,
    at: null,                 // the node you are standing on, null before you embark
    path: [],
    finished: false,
  };
}

/* -------------------------------------------------------------------- moving */

export function nodeById(chart, id) {
  for (const row of chart.rows) for (const n of row) if (n.id === id) return n;
  return null;
}

/** Where you may go next. Before you embark, that is the whole bottom row. */
export function reachable(chart) {
  if (!chart) return [];
  if (!chart.at) return chart.rows[0].slice();
  const cur = nodeById(chart, chart.at);
  if (!cur) return [];
  return cur.links.map((id) => nodeById(chart, id)).filter(Boolean);
}

export function canGo(chart, id) {
  return reachable(chart).some((n) => n.id === id);
}

export function travelTo(chart, id) {
  if (!canGo(chart, id)) return null;
  const n = nodeById(chart, id);
  chart.at = id;
  chart.path.push(id);
  return n;
}

/** Called when the stop is over, so the map can grey it out and know when the act is done. */
export function finishStop(chart) {
  const n = chart.at ? nodeById(chart, chart.at) : null;
  if (n) n.done = true;
  if (n && n.kind === 'boss') chart.finished = true;
  return chart.finished;
}

export function currentNode(chart) {
  return chart && chart.at ? nodeById(chart, chart.at) : null;
}

export function rowOf(chart) {
  const n = currentNode(chart);
  return n ? n.row : -1;
}

export function totalRows() { return ROWS; }
export function maxCols() { return MAX_COLS; }

/**
 * A quick honesty check on a generated chart, used by the tests and cheap enough to keep.
 * Returns a list of complaints; an empty list is a map you can play.
 */
export function auditChart(chart) {
  const bad = [];
  const all = [];
  for (const row of chart.rows) for (const n of row) all.push(n);
  for (const n of all) {
    if (n.row < ROWS - 1 && !n.links.length) bad.push(`${n.id} has no way on`);
    if (n.row > 0 && !all.some((m) => m.links.includes(n.id))) bad.push(`${n.id} has no way in`);
    for (const id of n.links) {
      const t = nodeById(chart, id);
      if (!t) { bad.push(`${n.id} links to nothing`); continue; }
      if (t.row !== n.row + 1) bad.push(`${n.id} links across ${t.row - n.row} rows`);
    }
  }
  // and no crossings: within a row, the leftmost target must never go backwards
  for (const row of chart.rows) {
    let floor = -1;
    for (const n of row) {
      const t = n.links.length ? nodeById(chart, n.links[0]) : null;
      if (!t) continue;
      if (t.col < floor) bad.push(`edges cross out of ${n.id}`);
      floor = t.col;
    }
  }
  if (chart.rows[ROWS - 1].length !== 1) bad.push('the boss row is not a single stop');
  if (chart.rows[ROWS - 1][0].kind !== 'boss') bad.push('the last stop is not the boss');
  if (!chart.rows[ROWS - 2].every((n) => n.kind === 'rest')) bad.push('no cove before the boss');
  if (!chart.rows[0].every((n) => n.kind === 'fight')) bad.push('the first row is not a shore');
  return bad;
}
